"""
Brand narrative generation for DJ Brand Guide Generator.

The narrative is generated by Claude in the API layer and passed via dj_data['brand_narrative'].
This module provides a fallback template for edge cases where no narrative is provided.
"""


def generate_brand_narrative(dj_data):
    """
    Return the brand narrative for the moodboard slide.

    The narrative is pre-generated by Claude in the API layer and passed
    via dj_data['brand_narrative']. Falls back to a template if not present.

    Args:
        dj_data: Dict containing DJ brand questionnaire data,
                 including 'brand_narrative' key with pre-generated text

    Returns:
        str: Two-paragraph brand narrative (~170 words)
    """
    # Use pre-generated narrative from dj_data (passed from API via dj_input_dict)
    if dj_data.get('brand_narrative'):
        return dj_data['brand_narrative']

    # Fallback: Simple template-based narrative
    return _generate_fallback_narrative(dj_data)


def _generate_fallback_narrative(dj_data):
    """
    Simple fallback narrative when no pre-generated narrative is available.

    This is a minimal template that covers the basic brand elements.
    The preferred path is always to use the Claude-generated narrative.
    """
    dj_name = dj_data.get('dj_name', 'The Artist')
    music_style = dj_data.get('music_style', 'electronic music')
    emotional_target = dj_data.get('emotional_target', 'a unique sonic experience')
    physical_place = dj_data.get('physical_place', 'an immersive environment')
    descriptors = dj_data.get('core_descriptors', ['immersive', 'intentional', 'evocative'])
    positioning = dj_data.get('brand_positioning', 'a unique sonic journey')

    # Get first few descriptors
    desc_str = ', '.join(descriptors[:3]) if descriptors else 'immersive, intentional'

    para1 = (
        f"This brand lives at the intersection of **{descriptors[0] if descriptors else 'depth'}** "
        f"and **{descriptors[1] if len(descriptors) > 1 else 'discovery'}**. "
        f"Its visual world is rooted in {physical_place} — compositions that evoke {emotional_target}. "
        f"The aesthetic is {desc_str}, reflecting the sonic identity of {music_style}."
    )

    para2 = (
        f"But within that foundation, there's contrast — moments of revelation that punctuate "
        f"the journey. {dj_name} embodies {positioning}, where every visual element serves "
        f"the story. It's a world that feels like **the space between notes — where anticipation "
        f"becomes its own reward**."
    )

    return f"{para1}\n\n{para2}"
